export const ADMIN_NAV_ITEMS = [
  { id: 'dashboard', label: 'Dashboard', icon: 'LayoutDashboard', href: '/admin' },
  { id: 'orders', label: 'Orders', icon: 'ClipboardList', href: '/admin/orders', badge: '12' },
  { id: 'menu', label: 'Menu', icon: 'Utensils', href: '/admin/menu' },
  { id: 'categories', label: 'Categories', icon: 'LayoutGrid', href: '/admin/categories' },
  { id: 'inventory', label: 'Inventory', icon: 'Package', href: '/admin/inventory' },
  { id: 'staff', label: 'Staff', icon: 'Users', href: '/admin/staff' },
  { id: 'customers', label: 'Customers', icon: 'Users2', href: '/admin/customers' },
  { id: 'revenue', label: 'Cash & Accounts', icon: 'Wallet', href: '/admin/revenue' },
  { id: 'promotions', label: 'Promotions', icon: 'Tag', href: '/admin/promotions' },
  { id: 'cms', label: 'CMS & Website', icon: 'Monitor', href: '/admin/cms' },
  { id: 'delivery', label: 'Delivery', icon: 'Bike', href: '/admin/delivery' },
  { id: 'tables', label: 'Tables', icon: 'Armchair', href: '/admin/tables' },
  { id: 'reports', label: 'Reports', icon: 'BarChart2', href: '/admin/reports' },
  { id: 'settings', label: 'Settings', icon: 'Settings', href: '/admin/settings' },
];

export const MOCK_BEST_SELLERS = [
  { id: 1, name: 'Chicken Biryani', orders: 124, revenue: 'Rs. 24,800', img: '/img/biryani.jpg' },
  { id: 2, name: 'Special Naan', orders: 96, revenue: 'Rs. 14,400', img: '/img/naan.jpg' },
  { id: 3, name: 'Chicken Karahi', orders: 72, revenue: 'Rs. 18,000', img: '/img/karahi.jpg' },
  { id: 4, name: 'Beef Seekh Kebab', orders: 58, revenue: 'Rs. 11,600', img: '/img/kebab.jpg' },
  { id: 5, name: 'Dal Makhani', orders: 46, revenue: 'Rs. 9,200', img: '/img/desi.jpg' },
];

export const MOCK_STOCK_ALERTS = [
  { name: 'Basmati Rice', qty: '3 kg left', status: 'Reorder soon', img: '/img/rice.jpg' },
  { name: 'Chicken (Fresh)', qty: '5 kg left', status: 'Reorder soon', img: '/img/chicken-special.jpg' },
  { name: 'Cooking Oil', qty: '2 bottles left', status: 'Low stock', img: '/img/mint.jpg' },
  { name: 'Tomatoes', qty: '4 kg left', status: 'Reorder soon', img: '/img/spread.jpg' },
  { name: 'Onions', qty: '6 kg left', status: 'Low stock', img: '/img/spread.jpg' },
];

export const MOCK_ORDERS = [
  {
    id: '#1042',
    customer: { name: 'Ali Raza', phone: '+92 300 1234567', avatar: 'AR' },
    itemsCount: 3,
    type: 'Dine In',
    table: 'Table 4',
    amount: 'Rs. 2,480',
    amountNum: 2480,
    payment: 'Paid',
    paymentMethod: 'Cash',
    status: 'Pending',
    time: '10:22 AM',
    notes: 'Less spicy for chicken karahi. Extra raita.',
    items: [
      { name: 'Chicken Biryani', variant: 'Regular Spicy', qty: 1, price: 820, img: '/img/biryani.jpg' },
      { name: 'Special Naan', variant: 'Garlic Naan', qty: 2, price: 300, img: '/img/naan.jpg' },
      { name: 'Chicken Karahi', variant: 'Full', qty: 1, price: 1200, img: '/img/karahi.jpg' },
    ],
    subtotal: 2320,
    tax: 160,
  },
  {
    id: '#1041',
    customer: { name: 'Sarah Khan', phone: '+92 321 9876543', avatar: 'SK' },
    itemsCount: 2,
    type: 'Delivery',
    table: '',
    amount: 'Rs. 1,250',
    amountNum: 1250,
    payment: 'Online',
    paymentMethod: 'Card',
    status: 'Preparing',
    time: '10:15 AM',
    notes: 'Please send cutlery and mint raita.',
    items: [
      { name: 'Chicken Biryani', variant: 'Spicy', qty: 2, price: 980, img: '/img/biryani.jpg' },
      { name: 'Fresh Lime Mint', variant: 'Chilled', qty: 1, price: 270, img: '/img/mint.jpg' },
    ],
    subtotal: 1150,
    tax: 100,
  },
  {
    id: '#1040',
    customer: { name: 'Ahmed Malik', phone: '+92 333 4567890', avatar: 'AM' },
    itemsCount: 4,
    type: 'Takeaway',
    table: '',
    amount: 'Rs. 980',
    amountNum: 980,
    payment: 'Paid',
    paymentMethod: 'Cash',
    status: 'Ready',
    time: '10:02 AM',
    notes: 'Pack hot in takeaway foil.',
    items: [
      { name: 'Beef Seekh Kebab', variant: 'Full plate', qty: 2, price: 700, img: '/img/kebab.jpg' },
      { name: 'Special Naan', variant: 'Plain', qty: 4, price: 280, img: '/img/naan.jpg' },
    ],
    subtotal: 900,
    tax: 80,
  },
  {
    id: '#1039',
    customer: { name: 'Fatima Noor', phone: '+92 300 2223344', avatar: 'FN' },
    itemsCount: 3,
    type: 'Delivery',
    table: '',
    amount: 'Rs. 1,680',
    amountNum: 1680,
    payment: 'COD',
    paymentMethod: 'Cash on Delivery',
    status: 'Preparing',
    time: '09:48 AM',
    notes: 'Ring bell on arrival.',
    items: [
      { name: 'Chicken Karahi', variant: 'Half', qty: 1, price: 900, img: '/img/karahi.jpg' },
      { name: 'Special Naan', variant: 'Butter', qty: 4, price: 380, img: '/img/naan.jpg' },
      { name: 'Fresh Salad & Raita', variant: 'Family', qty: 1, price: 400, img: '/img/desi.jpg' },
    ],
    subtotal: 1550,
    tax: 130,
  },
  {
    id: '#1038',
    customer: { name: 'Imran Sheikh', phone: '+92 321 1112233', avatar: 'IS' },
    itemsCount: 2,
    type: 'Dine In',
    table: 'Table 7',
    amount: 'Rs. 1,150',
    amountNum: 1150,
    payment: 'Paid',
    paymentMethod: 'Cash',
    status: 'Completed',
    time: '09:35 AM',
    notes: '',
    items: [
      { name: 'Chicken Biryani', variant: 'Special', qty: 1, price: 850, img: '/img/biryani.jpg' },
      { name: 'Lassi', variant: 'Sweet', qty: 1, price: 300, img: '/img/lassi.jpg' },
    ],
    subtotal: 1060,
    tax: 90,
  },
  {
    id: '#1037',
    customer: { name: 'Hassan Ali', phone: '+92 345 6677889', avatar: 'HA' },
    itemsCount: 3,
    type: 'Delivery',
    table: '',
    amount: 'Rs. 2,200',
    amountNum: 2200,
    payment: 'Online',
    paymentMethod: 'JazzCash',
    status: 'On the way',
    time: '09:28 AM',
    items: [],
  },
  {
    id: '#1036',
    customer: { name: 'Ayesha Siddiqui', phone: '+92 314 4455667', avatar: 'AS' },
    itemsCount: 2,
    type: 'Takeaway',
    table: '',
    amount: 'Rs. 760',
    amountNum: 760,
    payment: 'Paid',
    paymentMethod: 'Card',
    status: 'Completed',
    time: '09:12 AM',
    items: [],
  },
  {
    id: '#1035',
    customer: { name: 'Bilal Ahmed', phone: '+92 300 9988776', avatar: 'BA' },
    itemsCount: 3,
    type: 'Dine In',
    table: 'Table 2',
    amount: 'Rs. 1,960',
    amountNum: 1960,
    payment: 'Paid',
    paymentMethod: 'Cash',
    status: 'Cancelled',
    time: '08:55 AM',
    items: [],
  },
  {
    id: '#1034',
    customer: { name: 'Zara Khan', phone: '+92 333 1122334', avatar: 'ZK' },
    itemsCount: 2,
    type: 'Delivery',
    table: '',
    amount: 'Rs. 1,420',
    amountNum: 1420,
    payment: 'Online',
    paymentMethod: 'Online Banking',
    status: 'Completed',
    time: '08:40 AM',
    items: [],
  },
  {
    id: '#1033',
    customer: { name: 'Usman Raza', phone: '+92 323 5566778', avatar: 'UR' },
    itemsCount: 3,
    type: 'Takeaway',
    table: '',
    amount: 'Rs. 1,100',
    amountNum: 1100,
    payment: 'Paid',
    paymentMethod: 'Cash',
    status: 'Completed',
    time: '08:25 AM',
    items: [],
  },
];

export const MOCK_MENU_ITEMS = [
  {
    id: 'm1',
    name: 'Chicken Biryani',
    category: 'Rice',
    categoryKey: 'rice',
    veg: false,
    desc: 'Aromatic basmati rice cooked with tender chicken and traditional spices.',
    price: 600,
    featured: true,
    available: true,
    img: '/img/biryani.jpg',
    addons: 3,
    sizes: 2,
  },
  {
    id: 'm2',
    name: 'Special Naan',
    category: 'Breads',
    categoryKey: 'breads',
    veg: true,
    desc: 'Freshly baked naan with butter and sesame seeds.',
    price: 70,
    featured: false,
    available: true,
    img: '/img/naan.jpg',
    addons: 1,
    sizes: 1,
  },
  {
    id: 'm3',
    name: 'Chicken Karahi',
    category: 'Chicken',
    categoryKey: 'chicken',
    veg: false,
    desc: 'Traditional chicken karahi cooked with fresh tomatoes and spices.',
    price: 1200,
    featured: false,
    available: true,
    img: '/img/karahi.jpg',
    addons: 3,
    sizes: 2,
  },
  {
    id: 'm4',
    name: 'Dal Makhani',
    category: 'Rice',
    categoryKey: 'rice',
    veg: true,
    desc: 'Slow cooked black lentils with cream and butter.',
    price: 350,
    featured: false,
    available: true,
    img: '/img/desi.jpg',
    addons: 0,
    sizes: 2,
  },
  {
    id: 'm5',
    name: 'Beef Seekh Kebab',
    category: 'BBQ & Grill',
    categoryKey: 'bbq',
    veg: false,
    desc: 'Juicy minced beef kebabs with authentic spices.',
    price: 450,
    featured: false,
    available: false,
    img: '/img/kebab.jpg',
    addons: 2,
    sizes: 1,
  },
  {
    id: 'm6',
    name: 'Fresh Lime Mint',
    category: 'Drinks',
    categoryKey: 'drinks',
    veg: true,
    desc: 'Refreshing lime drink with fresh mint leaves.',
    price: 180,
    featured: false,
    available: true,
    img: '/img/mint.jpg',
    addons: 0,
    sizes: 2,
  },
];

export const MOCK_RAW_MATERIALS = [
  { id: 1, name: 'Basmati Rice', sku: 'BR-001', cat: 'Grains', unit: 'kg', stock: 3, reorder: 10, price: 'Rs. 180/kg', supplier: 'Al Noor Traders', status: 'Low Stock', low: true },
  { id: 2, name: 'Chicken (Fresh)', sku: 'CH-001', cat: 'Meat', unit: 'kg', stock: 5, reorder: 15, price: 'Rs. 420/kg', supplier: 'Fresh Foods Co.', status: 'Low Stock', low: true },
  { id: 3, name: 'Cooking Oil', sku: 'CO-001', cat: 'Oil & Spices', unit: 'ltr', stock: 2, reorder: 10, price: 'Rs. 320/ltr', supplier: 'National Foods', status: 'Low Stock', low: true },
  { id: 4, name: 'Tomatoes', sku: 'TO-001', cat: 'Vegetables', unit: 'kg', stock: 25, reorder: 10, price: 'Rs. 60/kg', supplier: 'Green Farm', status: 'In Stock', low: false },
  { id: 5, name: 'Onions', sku: 'ON-001', cat: 'Vegetables', unit: 'kg', stock: 6, reorder: 15, price: 'Rs. 50/kg', supplier: 'Green Farm', status: 'Low Stock', low: true },
  { id: 6, name: 'Yogurt', sku: 'YO-001', cat: 'Dairy', unit: 'kg', stock: 20, reorder: 10, price: 'Rs. 90/kg', supplier: 'Dairy Fresh', status: 'In Stock', low: false },
  { id: 7, name: 'Garam Masala', sku: 'GM-001', cat: 'Spices', unit: 'kg', stock: 8, reorder: 10, price: 'Rs. 380/kg', supplier: 'Spice World', status: 'Low Stock', low: true },
  { id: 8, name: 'Wheat Flour', sku: 'WF-001', cat: 'Grains', unit: 'kg', stock: 50, reorder: 20, price: 'Rs. 75/kg', supplier: 'Al Noor Traders', status: 'In Stock', low: false },
];

export const MOCK_STAFF = [
  { id: '#101', name: 'Ali Raza', role: 'Head Chef', section: 'Main Branch Kitchen', phone: '0300 1234567', email: 'ali.raza@alarabrestaurant.com', status: 'On Duty', shift: '9:00 AM - 5:00 PM', rating: 4.8, experience: '2 years', attendance: '98%', ordersHandled: 126, punctuality: '98%', feedback: 5, access: 'Kitchen Management', permissions: ['Manage Menu Items', 'Kitchen Orders', 'Inventory Access', 'View Reports'], branch: 'Main Branch' },
  { id: '#102', name: 'Sara Khan', role: 'Sous Chef', section: 'Main Branch Kitchen', phone: '0301 2345678', email: 'sara.k@alarabrestaurant.com', status: 'On Duty', shift: '9:00 AM - 5:00 PM', rating: 4.6 },
  { id: '#103', name: 'Ahmed Malik', role: 'Waiter', section: 'Main Branch Restaurant Floor', phone: '0302 3456789', email: 'ahmed.m@alarabrestaurant.com', status: 'On Duty', shift: '2:00 PM - 10:00 PM', rating: 4.5 },
  { id: '#104', name: 'Fatima Noor', role: 'Cashier', section: 'Main Branch Front Desk', phone: '0303 4567890', email: 'fatima.n@alarabrestaurant.com', status: 'On Duty', shift: '2:00 PM - 10:00 PM', rating: 4.7 },
  { id: '#105', name: 'Imran Sheikh', role: 'Kitchen Staff', section: 'Main Branch Kitchen', phone: '0304 5678901', email: 'imran.s@alarabrestaurant.com', status: 'Off Duty', shift: '--', rating: 4.2 },
  { id: '#106', name: 'Bilal Hussain', role: 'Waiter', section: 'Branch 2 Restaurant Floor', phone: '0305 6789012', email: 'bilal.h@alarabrestaurant.com', status: 'On Leave', shift: '--', rating: 4.3 },
  { id: '#107', name: 'Ayesha Malik', role: 'Host/Hostess', section: 'Main Branch Reception', phone: '0306 7890123', email: 'ayesha.m@alarabrestaurant.com', status: 'On Duty', shift: '10:00 AM - 6:00 PM', rating: 4.6 },
  { id: '#108', name: 'Usman Ali', role: 'Cleaner', section: 'Main Branch Maintenance', phone: '0307 8901234', email: 'usman.a@alarabrestaurant.com', status: 'On Duty', shift: '6:00 AM - 2:00 PM', rating: 4.1 },
  { id: '#109', name: 'Zain Abbas', role: 'Delivery Rider', section: 'Branch 2 Delivery', phone: '0308 9012345', email: 'zain.a@alarabrestaurant.com', status: 'Off Duty', shift: '--', rating: 4.4 },
  { id: '#110', name: 'Nimra Ahmed', role: 'Manager', section: 'Main Branch Management', phone: '0309 0123456', email: 'nimra.a@alarabrestaurant.com', status: 'On Duty', shift: '9:00 AM - 5:00 PM', rating: 4.9 },
];

export const MOCK_CUSTOMERS = [
  { id: 'c1', name: 'Ali Raza', phone: '+92 300 1234567', email: 'ali.raza@example.com', location: 'Karachi, Pakistan', tier: 'Gold', orders: 42, spent: 'Rs. 48,250', spentNum: 48250, points: '2,450', lastOrder: '8 Feb 2025', since: '12 Mar 2023', avgOrder: 'Rs. 1,148', referrals: 6, status: 'Active', segments: ['Frequent Diner', 'Family Customer', 'High Spender', 'Loves Biryani', 'Weekend Visitor'] },
  { id: 'c2', name: 'Sarah Khan', phone: '+92 321 9876543', email: 'sarah.khan@example.com', location: 'Karachi, Pakistan', tier: 'Gold', orders: 38, spent: 'Rs. 42,100', spentNum: 42100, points: '1,980', lastOrder: '7 Feb 2025', since: '05 Jan 2023', avgOrder: 'Rs. 1,107', referrals: 4, status: 'Active', segments: ['Frequent Diner', 'Online Delivery', 'Dessert Lover'] },
  { id: 'c3', name: 'Ahmed Malik', phone: '+92 333 4567890', email: 'ahmed.malik@example.com', location: 'Lahore, Pakistan', tier: 'Silver', orders: 35, spent: 'Rs. 36,900', spentNum: 36900, points: '1,620', lastOrder: '6 Feb 2025', since: '18 Apr 2023', avgOrder: 'Rs. 1,054', referrals: 3, status: 'Active', segments: ['Takeaway Fan', 'BBQ Lover'] },
  { id: 'c4', name: 'Fatima Noor', phone: '+92 300 2468135', email: 'fatima.noor@example.com', location: 'Islamabad, Pakistan', tier: 'Silver', orders: 28, spent: 'Rs. 32,400', spentNum: 32400, points: '1,350', lastOrder: '5 Feb 2025', since: '02 Jun 2023', avgOrder: 'Rs. 1,157', referrals: 2, status: 'Active', segments: ['Family Dining', 'Weekend Visitor'] },
  { id: 'c5', name: 'Imran Sheikh', phone: '+92 345 6789012', email: 'imran.sheikh@example.com', location: 'Karachi, Pakistan', tier: 'Bronze', orders: 25, spent: 'Rs. 28,750', spentNum: 28750, points: '1,120', lastOrder: '5 Feb 2025', since: '14 Aug 2023', avgOrder: 'Rs. 1,150', referrals: 1, status: 'Active', segments: ['Dine In Specialist', 'Spicy Food Lover'] },
  { id: 'c6', name: 'Ayesha Siddiqui', phone: '+92 321 5557788', email: 'ayesha.s@example.com', location: 'Rawalpindi, Pakistan', tier: 'Silver', orders: 22, spent: 'Rs. 24,600', spentNum: 24600, points: '980', lastOrder: '4 Feb 2025', since: '21 Sep 2023', avgOrder: 'Rs. 1,118', referrals: 2, status: 'Active', segments: ['Lunch Regular'] },
  { id: 'c7', name: 'Bilal Ahmed', phone: '+92 300 1122334', email: 'bilal.a@example.com', location: 'Karachi, Pakistan', tier: 'Bronze', orders: 18, spent: 'Rs. 19,200', spentNum: 19200, points: '720', lastOrder: '3 Feb 2025', since: '10 Nov 2023', avgOrder: 'Rs. 1,066', referrals: 0, status: 'Active', segments: ['Takeaway Fan'] },
  { id: 'c8', name: 'Sana Bukhari', phone: '+92 333 9988776', email: 'sana.b@example.com', location: 'Karachi, Pakistan', tier: 'Member', orders: 16, spent: 'Rs. 16,800', spentNum: 16800, points: '650', lastOrder: '2 Feb 2025', since: '05 Dec 2023', avgOrder: 'Rs. 1,050', referrals: 1, status: 'Active', segments: ['Occasional Diner'] },
];

export const MOCK_TRANSACTIONS = [
  { id: 'TXN1048', time: '10 Feb, 10:22 AM', desc: 'Table #12 - Order #1042', type: 'Income', amount: 'Rs. 2,450', method: 'Card', addedBy: 'Ali Raza' },
  { id: 'TXN1047', time: '10 Feb, 09:58 AM', desc: 'Online Order #1041', type: 'Income', amount: 'Rs. 1,680', method: 'Online', addedBy: 'Sarah Khan' },
  { id: 'TXN1046', time: '10 Feb, 09:35 AM', desc: 'Cash Sale - Table #8', type: 'Income', amount: 'Rs. 1,250', method: 'Cash', addedBy: 'Ahmed Malik' },
  { id: 'TXN1045', time: '10 Feb, 08:20 AM', desc: 'Supplier Payment - Meat', type: 'Expense', amount: 'Rs. 8,500', method: 'Cash', addedBy: 'Ahmed Khan' },
  { id: 'TXN1044', time: '09 Feb, 10:15 PM', desc: 'Staff Payout - Kitchen', type: 'Expense', amount: 'Rs. 12,000', method: 'Cash', addedBy: 'Ahmed Khan' },
  { id: 'TXN1043', time: '09 Feb, 09:45 PM', desc: 'Utility Bill - Electricity', type: 'Expense', amount: 'Rs. 5,600', method: 'Online', addedBy: 'Ahmed Khan' },
  { id: 'TXN1042', time: '09 Feb, 08:30 PM', desc: 'Table #6 - Order #1038', type: 'Income', amount: 'Rs. 1,920', method: 'Card', addedBy: 'Imran Sheikh' },
  { id: 'TXN1041', time: '09 Feb, 07:20 PM', desc: 'Cash Sale', type: 'Income', amount: 'Rs. 980', method: 'Cash', addedBy: 'Fatima Noor' },
];
